language: ruby
branches:
  only:
  - master
rvm:
- 2.3.3
addons:
  apt:
    packages:
    - sshpass
before_deploy:
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_10978a7f2d99_key -iv $encrypted_10978a7f2d99_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_10978a7f2d99_key -iv $encrypted_10978a7f2d99_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy\_rsa
- sshpass -p $SSH_PASSWORD ssh-add /tmp/deploy\_rsa
exclude:
- vendor
sudo: false
env:
  global:
  - secure: Bbv89jwTvEOb/VWiaO4g/7nLMQbPCAk2q9kOFvPcNIOG2c7cd9FjEST6RJumk1DhQaN9L3TJ519kl7Gneo/oWKG6SocQX2y6la4eQwkFLMEPXZRfpGP6PlyRb3Vn/L6T0UNT2peIF6PFJ5VkK2o8qJwXVGPiydPRHBdXgkJfMqhKBzyOQTDteYX0JhSOqZZZJcLtIQAlQ5Ep+2zhCemo/LjUAtIvgOrR0IB3wsmokF0DAvenwiA2blN8Bm8GBTvZock14MZ0mBir2N27jRer/ckEJ6tTmBjTEJH2YVJNIEKIzaIhZ/MTyHXFb4vBS/rxNYqHBcDVCQ8a1BspUz5OJZy04ccuuzGMNDpXbNOzSzWZs+I1+RaStDQHD1e4k/hAFpAzhZqQAXLAtWmPbABXdyIy+3bVPY3wiUBGNsFvkwTSAFWi+dJg0M1nBrRLDDzSGJPbzYdyiUoDqtVTwF22rjTJHs2g2Z5cV4C6yzcK7H5q2eGZIzoUx+hSk/BXDJkvvM5J6MXdG0DAz23k4VkQM7mwOwWtp5QHnjCWQqk8o1n+kE3oLrP3pE/7P4T8fpn/vKiBwYB3YS41AJV0RdNfR87ioUp9pkqTTPG+yPNlC0kj1TXUia5l6p3MKaNXL7xUzUI21ZJ8oLgV3b3JhgImbCHKbEzUfdcQrcm5hsRb6cg=
  - secure: tOk5ZVnJnAuNVkGwFTvayxIsqQkm5764f+qaU1w1nD3IRi4ZKnsbKAtsvJ4VUnMaM+vGd5v5jPb1DPr2Kw1czEKz656NLUrU96DFF7MdZaaJcDQ5FPDicFBBZRYF0dhsmyDla3rttM5YKjs4EwpCbB929+FOGjCCRw812l/yO5KTGEwI3dcU+AwHEwCuDtshYMQMeCEmjhI153tJJKHxQG/K7BOMTDo7qsvzsHH4Zh7oDW/Z5ldJMp8XSCCpdvWIRHm8sIi1f73mw/HfBZpM1NnRbbcDoAuWqsAGTz3kVNHHw58WFxZgdtjWpoR36Ee2a5ug4Y5mZdvYKu4Q8v3e9oY0EaaW0p63wPuANjrGG38qdxH8iylCkpBNglF06Tcg/oZTlUqnRFsXlNuV1kWWcv3LulhnCrDwICBJFuARH6CX4SV/9/b9V80bQqFobdSL/NdxWD3fTGZFCfTPfA593gx01esReqjZ6+CIwqnwGSDP/gg9ETmj6uJ7VqnTkCUAtqBWdVhPcduQB7I7eqNMTuC4N6oKcnvuhk/thUdeIDyLPfyOWnZNnI7FihiVvu7t2NnO9qVBscQRDIgzc12C5lc/C3ylXGpgAA2w5G8/zM6VAbew7ze0swIyxngqVL32Qy9wFO6Qqc1sfZHllHQxs+TzQET31OIEgB0pgXcUxks=
  - secure: tv7rYHVc460M25IGAMr8jbXMLe0ymobkWfGCRklQWjGVpKqXUf9hdfO1nE86pqW6KkkB+UuHYLj+K+lsPHag11PVhebOFDiPe/+b3kYpvk+meGhA0k0K8/wIPxVYIei6dtqXo3gB43OG4eLpgsTGtAUfqGjJNU9JD476Jn/qgHsuXhttvBMJmwco9F/UwclgqZfsgX2jGbnLLff5kfG3am/TiPn1iNYhf5m5efvYdTgvlGdCtSXag2V5Nk71SztiVmTuIF23+Iebtj9s6nyQR5n0nyDvBB79fn4+29QZ+4cVK2qIgz6z9AqkJqCtExHJHiTNWv3FR09XgRtHVd+SBMHT1m/oLasnutsMpG42iUhqMMQZvaHuY5jJ01D2/EoNTwnlrcceWFYtfHSxj8cvhr7JAWHwibfYRQ9ZU+dZgS0Vaf1vCBjHGaOfGASkzbIzBRNPbxpGXFuuuqtpNb/AubJFUSWzHzSoaZ9kvzYD1Ce+T2bTuG5neREA7YNZDs+CmRqnnz3trhKyRwG8iwSwa49KRdEKdX7lxjXJA2RVZVf72wOuaawjbtvG8lHNz6FwBp0G9+qrIattPb5EbtiPKowjdC0eotoZGi1tLsrUxDIprFI/q/Bj5E5nwOp6zqISDWXxwgBJgwGtwMAkbfUfHLf8VXv56JPijWHM6dJszhI=
  - secure: eRnnFYJX4t8I4AIAKEwsIUGlhTAby1nucA0hLYi+psJ77NL46ATTcewoDbrd0vZyu87jnAcn+x6tcVcOG+Rpo7Pcry3VnM7Swuhwhb+/wiGOMD+3S18S6u5UZPwvW0Krt6hFRou27kNR8EHR4hElUNovgX9hRgwRTC7Ip7moVcihoierzeDVAlKdUTSQQaaBAX4JNhN8dK1iM+D5iV0RlKx+Hp/vKyGoFHA81odwq3WUMZaYAE1SWA5cAH0mD+JHpbctEMZ0WNeiwBB1/of8ibwCJCWHWgAlMnKLeUmYBSNd/oYQsiZPz9sWWyJmDKbIIiPREI3uM8lwZZ2KHnrMor23VjgTRsDAxb6+Ig7HA/R7/jRlsc3UG4glUIDoIQE98S1Sb15taz50Cq0Ry1UZVOtv0XZhmQWXycK7BLqTbz9gjArZe87OV1HKD1u7ntYk2VBbwJyqyjbFOMCYC1AK217Ezf0jsy3pK1KQWiwyT3QI3sVCMDvNhY5BHi0bdJzZHSrEG9d5LGwt/Z9Nz+pfqkDCNcEKSKQpz1DlgICTXh7xyzyAvvZb7X6RHBxuAOrAYyovxw3Kq2pwQ3rj3puSv7dexAajQhTdRj2QwvvZC1ZVEUizYglNFC4J7IzC4oXbK3B8dk1gR2KL3LTxAPcqNecqYHxmTS+q/pTz25gvFQ8=
before_script:
- chmod +x ./script/cibuild
script: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./script/cibuild; fi
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
